# Generated by Django 4.2 on 2023-04-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuKassa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.DecimalField(blank=True, decimal_places=False, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='paymentModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.DecimalField(blank=True, decimal_places=False, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='paymentModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.DecimalField(blank=True, decimal_places=False, max_digits=100)),
            ],
        ),
        migrations.DeleteModel(
            name='paymentModel',
        ),
    ]
