# Generated by Django 4.2 on 2023-04-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuKassa', '0002_paymentmodel1_paymentmodel2_paymentmodel3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentModelAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.DecimalField(blank=True, decimal_places=False, max_digits=100)),
                ('field2', models.DecimalField(blank=True, decimal_places=False, max_digits=100)),
                ('field3', models.DecimalField(blank=True, decimal_places=False, max_digits=100)),
            ],
        ),
    ]
